# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: From Nothing to Something Development Blog
email: lukasolson@greyblockgames.com
description: >- # this means to ignore newlines until "baseurl:"
  The official developers blog from the upcoming indie video-game
  'From Nothing to Something'. Content is regularly added and documents
  the games development journey.
twitter_username: username
github_username: username
minimal_mistakes_skin: dark
search: true
locale: "en-US"

url: "https://n2s.greyblockgames.com"
repository: "greyblockgames/N2SBlog"

logo: "/assets/images/88x88.png"

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: America/Vancouver # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Lukas Olson"
  avatar : "/assets/images/bio-photo.jpg"
  bio    : "My name is Luke and I'm the lead developer on From Nothing to Something."
  links:
    - label: "My Personal Website"
      icon: "fas fa-fw fa-link"
      url: "https://olson.greyblockgames.com"
    - label: "Steam"
      icon: "fab fa-fw fa-steam-square"
      url: "https://steamcommunity.com/id/lukasolson/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/lukasdragon"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/lukasgoalson"

footer:
  links:
    - label: "Website"
      icon: "fab fa-fw fa-link"
      url: "https://greyblockgames.com/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/greyblockgames"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
  
  
comments:
    provider: "disqus"
    disqus:
        shortname: "n2sblog"
